apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base

images:
- name: PROJECT/backend-todos
  newName: shehzadkhuwaja/backend-todos
  newTag: 415bba3c213fc4bb6f271a5bf8bdac611431be6f
- name: PROJECT/broadcaster
  newName: shehzadkhuwaja/broadcaster
  newTag: 415bba3c213fc4bb6f271a5bf8bdac611431be6f
- name: PROJECT/todo-cronjob
  newName: shehzadkhuwaja/todo-cronjob
  newTag: 415bba3c213fc4bb6f271a5bf8bdac611431be6f
- name: PROJECT/todoapp
  newName: shehzadkhuwaja/todoapp
  newTag: 415bba3c213fc4bb6f271a5bf8bdac611431be6f
- name: PROJECT/todoappfrontend
  newName: shehzadkhuwaja/todoappfrontend
  newTag: 415bba3c213fc4bb6f271a5bf8bdac611431be6f
