apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  namespace: project
data:
  PORT: "3001"
  NODE_ENV: "production"
  CORS_ORIGIN: "http://frontend.project.svc.cluster.local"
  PGUSER: "todoappuser"
  PGDATABASE: "tododb"
  PGPORT: "80"
  PGHOST: "postgres-svc" # reason for not using postgres-svc.project.svc.cluster.local is so that it can be injected dynamically as per environment
  GCS_BUCKET: "todo-db-backups-mooc"
  NATS_URL: "nats://my-nats.nats.svc.cluster.local:4222"
