apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: project
data:
  IMAGE_URL: "https://picsum.photos/1200"
  IMAGE_EXPIRY_MINUTES: "10"
  IMAGE_FILE: "/shared/image.jpg"
  META_FILE: "/shared/meta.json"
  PORT: "3000"