apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: project
spec:
  rules:
  - http:
      paths:
      - path: /api/todos
        pathType: Prefix
        backend:
          service:
            name: backend-todos
            port:
              number: 2345
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 2345
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 2345