apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: todoapp-route
  namespace: project
spec:
  parentRefs:
  - name: todoapp-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: frontend-svc
      port: 80
  
  - matches:
      - path:
          type: PathPrefix
          value: /helloworld
    backendRefs:
      - name: backend-todos-svc
        port: 80

  - matches:
    - path:
        type: PathPrefix
        value: /api/todos
    backendRefs:
      - name: backend-todos-svc
        port: 80

  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
      - name: backend-svc
        port: 80