apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/broadcaster-deployment.yaml
  - manifests/backend-config-map.yaml
  - manifests/backup-cronjob.yaml
  - manifests/backend-deployment.yaml
  - manifests/backend-service.yaml
  - manifests/postgres-init-config.yaml
  - manifests/backend-todos-config-map.yaml
  - manifests/backend-todos-deployment.yaml
  - manifests/backend-todos-service.yaml
  - manifests/frontend-config-map.yaml
  - manifests/frontend-deployment.yaml
  - manifests/frontend-service.yaml
  - manifests/gateway.yaml
  - manifests/postgres-stateful-set.yaml
  - manifests/route.yaml
  - manifests/todo-cronjob.yaml
  - Persistent/persistentvolumeclaim.yaml
